//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _STM32TEST_H_
#define _STM32TEST_H_

#include <TinyCLR_Interop.h>
struct Library_STM32Test_MFConsoleApplication1_Program
{
    static const int FIELD_STATIC__Green = 0;
    static const int FIELD_STATIC__Orange = 1;
    static const int FIELD_STATIC__Red = 2;
    static const int FIELD_STATIC__Blue = 3;
    static const int FIELD_STATIC__pushBtn = 4;
    static const int FIELD_STATIC__serialPort1 = 5;
    static const int FIELD_STATIC__serialPort2 = 6;
    static const int FIELD_STATIC__RTS = 7;
    static const int FIELD_STATIC__CTS = 8;
    static const int FIELD_STATIC__serialPortFailure = 9;
    static const int FIELD_STATIC__<hold>k__BackingField = 10;
    static const int FIELD_STATIC__<inside>k__BackingField = 11;


    //--//

};

struct Library_STM32Test_MFConsoleApplication1_Resources
{
    static const int FIELD_STATIC__manager = 12;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_STM32Test;

#endif  //_STM32TEST_H_
